/**
 * Slice 7 — Persona Generation Skill · e2e spec.
 *
 * Verifies that an agent generated by the agent.create skill chain renders
 * correctly in the live dashboard:
 *
 *   1. The agent appears in /api/agents (via the agents listing UI).
 *   2. The agent's detail/files page loads without console errors.
 *   3. The Persona tab renders the generated CLAUDE.md (not just an empty
 *      Monaco buffer).
 *   4. The Config tab renders the generated agent.yaml with all Slice-1
 *      keys present.
 *   5. The avatar URL responds (200) and is a valid image.
 *
 * Pre-conditions for the run:
 *   - The persona-scaffold CLI has been invoked against the live agents/
 *     directory. For a non-destructive run, we point the dashboard at
 *     CLAUDECLAW_CONFIG=proof/slice-7/sample-generation so the generated
 *     test agent (deliverability-expert) is visible without touching the
 *     production agents/ tree.
 *   - The dashboard is running on http://localhost:5173 (or DASHBOARD_URL).
 *   - For the Slice 7 happy-path render, the test agent's avatar.png and
 *     agent.yaml exist on disk.
 *
 * This file is committed as documentation for the test plan. Like
 * Slice 1's spec, the actual run is performed via the Playwright MCP
 * tools in the implementation worktree (mcp__plugin_playwright_*).
 */
import { test, expect } from '@playwright/test';

const DASHBOARD = process.env.DASHBOARD_URL ?? 'http://localhost:5173';
const AGENT = process.env.SLICE_7_AGENT ?? 'deliverability-expert';

test.describe('Slice 7 — Persona Generation Skill', () => {
  test('generated agent renders in the dashboard with no console errors', async ({ page }) => {
    const consoleErrors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'error') consoleErrors.push(msg.text());
    });
    page.on('pageerror', (err) => consoleErrors.push(`pageerror: ${err.message}`));

    // 1. Land on the agents list. The Slice 1 work surfaces every agent
    //    here from /api/agents.
    await page.goto(`${DASHBOARD}/agents`);
    await expect(page.getByText(/Agents/i)).toBeVisible({ timeout: 10_000 });

    // 2. Navigate directly to the generated agent's files page (the URL
    //    is stable regardless of the listing's ordering).
    await page.goto(`${DASHBOARD}/agents/${AGENT}/files`);
    await page.waitForSelector('.monaco-editor', { timeout: 15_000 });

    // 3. Persona tab loads with the generated CLAUDE.md content.
    await expect(page.getByRole('button', { name: /Persona \(CLAUDE\.md\)/ })).toBeVisible();
    const personaText = await page.evaluate(() =>
      (window as any).monaco?.editor?.getModels()?.[0]?.getValue() ?? ''
    );
    // The generator always emits these section headings.
    expect(personaText).toMatch(/## What you handle/);
    expect(personaText).toMatch(/## Results you're accountable for/);
    expect(personaText).toMatch(/## Style/);
    expect(personaText).toMatch(/## Hard rules/);
    expect(personaText).toMatch(/## Background/);
    // House style defaults applied.
    expect(personaText).toMatch(/No em dashes/);
    expect(personaText).toMatch(/No AI clichés/);

    // 4. Config tab renders the generated agent.yaml with all Slice 1 keys.
    await page.getByRole('button', { name: /Config \(agent\.yaml\)/ }).click();
    await page.waitForFunction(
      () => (window as any).monaco?.editor?.getModels()?.[0]?.getValue()?.includes('telegram_bot_token_env'),
      { timeout: 10_000 }
    );
    const yamlText = await page.evaluate(() =>
      (window as any).monaco.editor.getModels()[0].getValue()
    );
    for (const key of ['four_rs:', 'owns:', 'lob:', 'projects:', 'ideal:', 'platform:', 'skills:', 'avatar:']) {
      expect(yamlText).toContain(key);
    }
    // Description should be the generated one-liner, not the Slice-1 default.
    expect(yamlText).toMatch(/description:/);

    // 5. Avatar endpoint responds with image bytes.
    const avatarResp = await page.request.get(`${DASHBOARD}/api/agents/${AGENT}/avatar`);
    expect(avatarResp.status()).toBe(200);
    const ct = avatarResp.headers()['content-type'] ?? '';
    expect(ct).toMatch(/image\/(png|jpeg|webp)/);
    const bytes = await avatarResp.body();
    expect(bytes.length).toBeGreaterThan(100);

    // 6. No console errors at any step.
    expect(consoleErrors, `console errors: ${consoleErrors.join(' | ')}`).toEqual([]);
  });
});
