/**
 * Slice 7: Persona Generation Skill, e2e spec.
 *
 * Verifies that an agent generated by the agent.create skill chain renders
 * correctly in the live dashboard. Acceptance criterion from the spec:
 * "Output renders correctly in the agent detail page (Slice 1) AND org
 * chart (Slice 3)."
 *
 *   1. /agents listing (Slice 1): the generated agent appears with its
 *      display name or slug; user can find it without knowing the URL.
 *   2. /agents/<slug>/files detail page (Slice 1): both Persona and Config
 *      tabs load without errors.
 *   3. Persona tab: Monaco renders the generated CLAUDE.md (not an empty
 *      buffer); house-style sections (What you handle, Results, Style,
 *      Hard rules, Background) and house-style rules ("No em dashes",
 *      "No AI clichés") all present; the rendered persona itself
 *      contains zero U+2014 characters.
 *   4. Config tab: Monaco renders the generated agent.yaml with every
 *      Slice-1 key (four_rs, owns, lob, projects, ideal, platform,
 *      skills, avatar) present.
 *   5. Avatar endpoint /api/agents/<slug>/avatar responds 200 with image
 *      bytes.
 *   6. Cross-cutting: zero console errors and zero pageerrors captured at
 *      any point during the run.
 *
 * Pre-conditions for the run:
 *   - The persona-scaffold CLI has been invoked against the live agents/
 *     directory. For a non-destructive run, point the dashboard at
 *     CLAUDECLAW_CONFIG=proof/slice-7/sample-generation so the generated
 *     test agent (deliverability-expert) is visible without touching the
 *     production agents/ tree.
 *   - The dashboard is running on http://localhost:5173 (or DASHBOARD_URL).
 *   - The generated agent's avatar.png and agent.yaml exist on disk.
 *
 * This file is committed as the canonical CI / on-demand spec. Like
 * Slice 1's spec, ad-hoc local runs are also performed via the Playwright
 * MCP tools in the implementation worktree (mcp__plugin_playwright_*).
 */
import { test, expect } from '@playwright/test';

const DASHBOARD = process.env.DASHBOARD_URL ?? 'http://localhost:5173';
const AGENT = process.env.SLICE_7_AGENT ?? 'deliverability-expert';
const AGENT_DISPLAY_NAME = process.env.SLICE_7_AGENT_DISPLAY_NAME ?? 'Deliverability Expert';

test.describe('Slice 7: Persona Generation Skill', () => {
  test('generated agent renders in /agents listing and detail page with no console errors', async ({ page }) => {
    const consoleErrors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'error') consoleErrors.push(msg.text());
    });
    page.on('pageerror', (err) => consoleErrors.push(`pageerror: ${err.message}`));

    // 1. The /agents listing (Slice 1) must surface the generated agent.
    //    Acceptance: the user can find it without knowing the URL.
    await page.goto(`${DASHBOARD}/agents`);
    await expect(page.getByText(/Agents/i).first()).toBeVisible({ timeout: 10_000 });
    // Wait for the listing to populate from /api/agents.
    await page.waitForFunction(
      (slug: string) => document.body.innerText.includes(slug),
      AGENT,
      { timeout: 10_000 },
    );
    // Assert the generated agent appears in the listing by display name OR slug.
    // AgentCard renders `agent.name || agent.id`, so either is acceptable.
    const listingBody = await page.evaluate(() => document.body.innerText);
    const listingHasAgent =
      listingBody.includes(AGENT_DISPLAY_NAME) || listingBody.includes(AGENT);
    expect(
      listingHasAgent,
      `expected /agents listing to contain "${AGENT_DISPLAY_NAME}" or "${AGENT}"`,
    ).toBe(true);

    // 2. Detail page (Slice 1): /agents/<slug>/files. Persona + Config tabs
    //    must both load without console errors.
    await page.goto(`${DASHBOARD}/agents/${AGENT}/files`);
    await page.waitForSelector('.monaco-editor', { timeout: 15_000 });

    // 3. Persona tab loads with the generated CLAUDE.md content.
    await expect(page.getByRole('button', { name: /Persona \(CLAUDE\.md\)/ })).toBeVisible();
    const personaText = await page.evaluate(() =>
      (window as any).monaco?.editor?.getModels()?.[0]?.getValue() ?? ''
    );
    // The generator always emits these section headings.
    expect(personaText).toMatch(/## What you handle/);
    expect(personaText).toMatch(/## Results you're accountable for/);
    expect(personaText).toMatch(/## Style/);
    expect(personaText).toMatch(/## Hard rules/);
    expect(personaText).toMatch(/## Background/);
    // House style defaults applied.
    expect(personaText).toMatch(/No em dashes/);
    expect(personaText).toMatch(/No AI clichés/);
    // House style enforcement: the generated persona itself must not contain
    // em dashes (U+2014).
    expect(personaText).not.toMatch(/—/);

    // 4. Config tab renders the generated agent.yaml with all Slice 1 keys.
    await page.getByRole('button', { name: /Config \(agent\.yaml\)/ }).click();
    await page.waitForFunction(
      () => (window as any).monaco?.editor?.getModels()?.[0]?.getValue()?.includes('telegram_bot_token_env'),
      { timeout: 10_000 }
    );
    const yamlText = await page.evaluate(() =>
      (window as any).monaco.editor.getModels()[0].getValue()
    );
    // The Slice-7 generator must populate every Slice-1 key, including the
    // newly-introduced four_rs / owns / lob / projects / ideal / platform /
    // skills / avatar block.
    for (const key of [
      'four_rs:',
      'owns:',
      'lob:',
      'projects:',
      'ideal:',
      'platform:',
      'skills:',
      'avatar:',
    ]) {
      expect(yamlText, `agent.yaml missing key "${key}"`).toContain(key);
    }
    // Description should be the generated one-liner, not the Slice-1 default.
    expect(yamlText).toMatch(/description:/);

    // 5. Avatar endpoint responds with image bytes.
    const avatarResp = await page.request.get(`${DASHBOARD}/api/agents/${AGENT}/avatar`);
    expect(avatarResp.status()).toBe(200);
    const ct = avatarResp.headers()['content-type'] ?? '';
    expect(ct).toMatch(/image\/(png|jpeg|webp)/);
    const bytes = await avatarResp.body();
    expect(bytes.length).toBeGreaterThan(100);

    // 6. No console errors captured at any step (listing, detail, tab switch,
    //    avatar fetch). This is the cross-cutting acceptance check.
    expect(
      consoleErrors,
      `console errors captured during run: ${consoleErrors.join(' | ')}`,
    ).toEqual([]);
  });
});
